
OUTPUT: 
  OUTPUT_DIR: '/home/schobs/Documents/PhD/local_LaNNU-Net/outputs/toms/test' #change this to where you have the data
  USE_COMETML_LOGGING: False
  COMET_API_KEY: ""
  COMET_WORKSPACE: ""
  COMET_TAGS: ["phdnet", "test"]
  

SOLVER:
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE_TRAIN: 12
  MAX_EPOCHS: 500
  AUTO_MIXED_PRECISION: False
  MINI_BATCH_SIZE:  1

  DEEP_SUPERVISION: False
  NUM_RES_SUPERVISIONS: 1  
  BASE_LR: 0.001  # Initial learning rate

  

MODEL:
  GAUSS_SIGMA: 2
  ARCHITECTURE: "PHD-Net"
  # CHECKPOINT: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/ISBI/testing/phdnet_ISBI_2GS_AugAC_L0_nolog_full/model_latest_fold0.model"
  HM_LAMBDA_SCALE: 1.0
  PHDNET:
    LOG_TRANSFORM_DISPLACEMENTS: True

DATASET:
  # ROOT: '/home/schobs/Documents/PhD/data/ISBI2015_landmarks/' #change this to where you have the data
  # SRC_TARGETS: '/home/schobs/Documents/PhD/data/ISBI2015_landmarks/lann_folds/w_valid' #change this
  ROOT: '/mnt/bess/shared/ai4h/Shared/Data/medical/CMRI/ASPIRE/'
  SRC_TARGETS: '/mnt/bess/shared/ai4h/Shared/Data/medical/CMRI/ASPIRE/cardiac4ch_labels_VPnC_CV'
  NAME:  "APSIRE_MEDIUM_4CH"
  IMAGE_MODALITY: 'CMRI'
  TRAINSET_SIZE: 10
  # LANDMARKS : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
  LANDMARKS : [0]



SAMPLER:
  DATA_AUG: None
  INPUT_SIZE : [512,512]
  SAMPLE_MODE: 'patch_bias' # ['patch', 'full']
  NUM_WORKERS: 8
  DEBUG: False
  PATCH:
    SAMPLER_BIAS: 0.66
    RESOLUTION_TO_SAMPLE_FROM:  "input_size" # ['full', 'input_size']
    SAMPLE_PATCH_SIZE: [128,128]
    # EVALUATION_SAMPLE_MODE: "full"  # ['patch', "full"] Whether to sample patches or the full image during evaluation



TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False
  CACHE_DATA: True
  INFERENCE_ONLY: False

INFERENCE:
  EVALUATION_MODE: "scale_heatmap_first" # ["scale_heatmap_first", "scale_pred_coords", "use_input_size"]
  DEBUG: False
