
 
OUTPUT: 
  OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFU4CH_8GS_testing"
  USE_COMETML_LOGGING: True
  COMET_API_KEY: "B5Nk91E6iCmWvBznXXq3Ijhhp"
  COMET_WORKSPACE: "schobs"
 

SOLVER:
  DEEP_SUPERVISION: True
  NUM_RES_SUPERVISIONS: 5
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE_TRAIN: 32



MODEL:
  GAUSS_SIGMA: 8

DATASET:
  # DEBUG: True
  ROOT: '/shared/tale2/Shared/data/CMRI/'
  SRC_TARGETS: '/shared/tale2/Shared/data/CMRI/PAH-Followup/landmark_localisation_annotations_combined_npz/4ch'
  NAME:  "APSIRE_MEDIUM_4CH"
  IMAGE_MODALITY: 'CMRI'
  LANDMARKS : [0,1,2,3,]
    
 
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False
  INFERENCE_ONLY: False
  CACHE_DATA: True

INFERENCE:
  EVALUATION_MODE: "scale_heatmap_first" # ["scale_heatmap_first", "scale_pred_coords", "use_input_size"]
  DEBUG: False

SAMPLER:
  NUM_WORKERS: 8
  DATA_AUG: 'AffineComplex'
  INPUT_SIZE : [512,512]

  #TODO: boolean for performing validation or not. its false in the isbi one because it is tested di

  
 

# SOLVER:
#   DEEP_SUPERVISION: True
#   NUM_RES_SUPERVISIONS: 5
#   LOSS_FUNCTION: "mse"
#   DATA_LOADER_BATCH_SIZE_TRAIN: 32


# MODEL:
#   GAUSS_SIGMA: 8

# DATASET:
#   # DEBUG: True
#   ROOT: '/shared/tale2/Shared/data/CMRI/'
#   SRC_TARGETS: '/shared/tale2/Shared/data/CMRI/PAH-Followup/landmark_localisation_annotations_combined_npz/4ch'
#   NAME:  "APSIRE_MEDIUM_4CH"
#   IMAGE_MODALITY: 'CMRI'
#   LANDMARKS : [0,1,2,3,]
#     
 
# TRAINER:
#   PERFORM_VALIDATION: True
#   SAVE_LATEST_ONLY: False
#   INFERENCE_ONLY: True
#   CACHE_DATA: False

# INFERENCE:
#   EVALUATION_MODE: "scale_heatmap_first" # ["scale_heatmap_first", "scale_pred_coords", "use_input_size"]
#   DEBUG: False
#   ENSEMBLE_INFERENCE: True # average predictions from multiple models
#   ENSEMBLE_CHECKPOINTS: 
#     [
#       '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFU4CH_8GS/model_best_valid_coord_error_fold0.model',
#       '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFU4CH_8GS/model_best_valid_coord_error_fold1.model',
#       '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFU4CH_8GS/model_best_valid_coord_error_fold2.model',
#       '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFU4CH_8GS/model_best_valid_coord_error_fold3.model',
#       '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFU4CH_8GS/model_best_valid_coord_error_fold4.model',
#       '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFU4CH_8GS/model_best_valid_coord_error_fold5.model',
#       '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFU4CH_8GS/model_best_valid_coord_error_fold6.model',
#       '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFU4CH_8GS/model_best_valid_coord_error_fold7.model',
#       '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFU4CH_8GS/model_best_valid_coord_error_fold8.model',
#       '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFU4CH_8GS/model_best_valid_coord_error_fold9.model',
#       '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFU4CH_8GS/model_best_valid_coord_error_fold99.model',
#     ] # list of checkpoints to ensemble

# SAMPLER:
#   NUM_WORKERS: 8
#   DATA_AUG: 'AffineComplex'
#   INPUT_SIZE : [512,512]

# OUTPUT:
#   COMET_TAGS: ["comet_test"]
#   #TODO: boolean for performing validation or not. its false in the isbi one because it is tested directly instead.