
 
OUTPUT: 
  OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/M4CH/testing/nnuent/M4CH_nnunet_2GS_AugAC_CV_F"

 

SOLVER:
  DEEP_SUPERVISION: True
  NUM_RES_SUPERVISIONS: 5
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE: 32



MODEL:
  GAUSS_SIGMA: 2

DATASET:
  # DEBUG: True
  ROOT: '/shared/tale2/Shared/data/CMRI/PAH-Baseline/Proc/4ch'
  SRC_TARGETS: '/shared/tale2/Shared/data/CMRI/PAH-Baseline/Proc/landmark_localisation_annotations/4ch'
  NAME:  "APSIRE_MEDIUM_4CH"
  IMAGE_MODALITY: 'CMRI'
  LANDMARKS : [0,1,2,3,]
  ORIGINAL_IMAGE_SIZE : [512,512]
  
 
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False
  INFERENCE_ONLY: False
  CACHE_DATA: True

INFERENCE:
  EVALUATION_MODE: "scale_heatmap_first" # ["scale_heatmap_first", "scale_pred_coords", "use_input_size"]
  DEBUG: False

SAMPLER:
  NUM_WORKERS: 8
  DATA_AUG: 'AffineComplex'
  INPUT_SIZE : [512,512]

  #TODO: boolean for performing validation or not. its false in the isbi one because it is tested directly instead.