
OUTPUT: 
  OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/M4CH/testing/phdnet/M4CH_phdnet_2GS_AugAC_L0_test"
  USE_COMETML_LOGGING: True
  COMET_API_KEY: "B5Nk91E6iCmWvBznXXq3Ijhhp"
  COMET_WORKSPACE: "schobs"
  COMET_TAGS: ["phdnet", "test"]
  

SOLVER:
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE: 12
  MAX_EPOCHS: 500
  REGRESS_SIGMA: False
  REGRESS_SIGMA_LOSS_WEIGHT: 0.005
  AUTO_MIXED_PRECISION: False
  MINI_BATCH_SIZE:  1

  DEEP_SUPERVISION: False
  NUM_RES_SUPERVISIONS: 1  
  BASE_LR: 0.001  # Initial learning rate

  
# /mnt/bess/home/acq19las/landmark_unet/LaNNU-Net/outputsISBI/v2/ISBI_512F_512Res_3GS_4MFR_AugACEBS_DS5

MODEL:
  GAUSS_SIGMA: 2
  ARCHITECTURE: "PHD-Net"
  #model_latest_fold0
  # CHECKPOINT: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/ISBI/testing/phdnet_ISBI_2GS_AugAC_L0_nolog_full/model_latest_fold0.model"
  HM_LAMBDA_SCALE: 1.0
  PHDNET:
    LOG_TRANSFORM_DISPLACEMENTS: True

DATASET:
  ROOT: '/shared/tale2/Shared/data/CMRI/PAH-Baseline/Proc/4ch'
  SRC_TARGETS: '/shared/tale2/Shared/data/CMRI/PAH-Baseline/Proc/landmark_localisation_annotations/4ch'
  NAME:  "APSIRE_MEDIUM_4CH"
  IMAGE_MODALITY: 'CMRI'
  # LANDMARKS : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
  LANDMARKS : [0]

    # TRAINSET_SIZE: 1


SAMPLER:
  DATA_AUG: 'AffineComplex'
  INPUT_SIZE : [512,512]
  SAMPLE_MODE: 'patch' # ['patch', 'full']
  NUM_WORKERS: 8
  DEBUG: False
  PATCH:
    SAMPLER_BIAS: 0.0
    RESOLUTION_TO_SAMPLE_FROM:  "input_size" # ['full', 'input_size']
    SAMPLE_PATCH_SIZE: [128,128]
    EVALUATION_SAMPLE_MODE: "full"  # ['patch', "full"] Whether to sample patches or the full image during evaluation


# _C.SAMPLER.PATCH = CN() 
# _C.SAMPLER.PATCH.SAMPLE_PATCH_SIZE = [512,512]
# _C.SAMPLER.PATCH.SAMPLE_FROM_RESOLUTION = _C.DATASET.# _C.SAMPLER.PATCH.SAMPLER_BIAS = 0.66
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False
  CACHE_DATA: True

  INFERENCE_ONLY: False

INFERENCE:
  EVALUATION_MODE: "use_input_size" # ["scale_heatmap_first", "scale_pred_coords", "use_input_size"]
  DEBUG: False
