
 
OUTPUT: 
  OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/april/BFUSA_8GS_ensemble_LARGE_inference_prasun_april23"
  COMET_TAGS: ["comet_aspire_large_prasun_APRIL"]

 

SOLVER:
  DEEP_SUPERVISION: True
  NUM_RES_SUPERVISIONS: 5
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE_TRAIN: 32



MODEL:
  GAUSS_SIGMA: 8

DATASET:
  # DEBUG: True
  ROOT: '/shared/tale2/Shared/data/CMRI/'
  # SRC_TARGETS: '/shared/tale2/Shared/data/CMRI/PAH-Followup/landmark_localisation_annotations_combined_npz/4ch'
  SRC_TARGETS: '/shared/tale2/Shared/data/CMRI/new scans/SArecipe/fold0.json'

  NAME:  "APSIRE_SA_APRIL"
  IMAGE_MODALITY: 'CMRI'
  LANDMARKS : [0,1,2,3,]
  DATASET_CLASS: "aspire"
 
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False
  INFERENCE_ONLY: True
  CACHE_DATA: False
  FOLD: -1 #no cv

MODEL:
  CHECKPOINT: '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold0.model'

INFERENCE:
  EVALUATION_MODE: "scale_heatmap_first" # ["scale_heatmap_first", "scale_pred_coords", "use_input_size"]
  DEBUG: False
  ENSEMBLE_INFERENCE: True # average predictions from multiple models
  ENSEMBLE_CHECKPOINTS: 
    [
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold0.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold1.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold2.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold3.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold4.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold5.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold6.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold7.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold8.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold9.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold99.model',

    ] # list of checkpoints to ensemble

SAMPLER:
  NUM_WORKERS: 2
  DATA_AUG: 'AffineComplex'
  INPUT_SIZE : [512,512]

# SSH:
#   AUTO_AMEND_PATHS: False