
# OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/ISBI/param_search/ISBI_512F_512Res_3GS_4MFR_AugAC_DS5"
OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS_ensemble_LARGE_inference_prasun"

# OUTPUT_DIR: "/home/schobs/Documents/PhD/landmark_ensemble/outputs/4CH_256F_256Res_8GS_AugV1"

SOLVER:
  DEEP_SUPERVISION: True
  NUM_RES_SUPERVISIONS: 5
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE: 32



MODEL:
  GAUSS_SIGMA: 8

DATASET:
  # DEBUG: True
  ROOT: '/shared/tale2/Shared/data/CMRI/'
  # SRC_TARGETS: '/shared/tale2/Shared/data/CMRI/PAH-Followup/landmark_localisation_annotations_combined_npz/4ch'
  SRC_TARGETS: '/shared/tale2/Shared/data/CMRI/PAH-Large/landmark_localisation_annotations/SA/fold0_nodups.json'
  NAME:  "APSIRE_LARGE_4CH"
  IMAGE_MODALITY: 'CMRI'
  LANDMARKS : [0,1,2,3,]
  ORIGINAL_IMAGE_SIZE : [512,512]
  DATASET_CLASS: "aspire"
 
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False
  INFERENCE_ONLY: True
  CACHE_DATA: False
  FOLD: -1 #no cv

MODEL:
  CHECKPOINT: '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold0.model'

INFERENCE:
  EVALUATION_MODE: "scale_heatmap_first" # ["scale_heatmap_first", "scale_pred_coords", "use_input_size"]
  DEBUG: False
  ENSEMBLE_INFERENCE: True # average predictions from multiple models
  ENSEMBLE_CHECKPOINTS: 
    [
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold0.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold1.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold2.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold3.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold4.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold5.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold6.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold7.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold8.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold9.model',
      '/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/BFUSA_8GS/model_best_valid_coord_error_fold99.model',

    ] # list of checkpoints to ensemble

SAMPLER:
  NUM_WORKERS: 8
  DATA_AUG: 'AffineComplex'
  INPUT_SIZE : [512,512]

OUTPUT:
  COMET_TAGS: ["comet_aspire_large_prasun"]
  #TODO: boolean for performing validation or not. its false in the isbi one because it is tested directly instead.