
 
OUTPUT: 
  OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/MSA/testing/nnuent/MSA_nnunet_8GS_AugAC_CV"

 

SOLVER:
  DEEP_SUPERVISION: True
  NUM_RES_SUPERVISIONS: 5
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE: 1



MODEL:
  GAUSS_SIGMA: 8

DATASET:
  # DEBUG: True
  ROOT: '/shared/tale2/Shared/data/CMRI/PAH-Followup/SA_resized'
  # SRC_TARGETS: '/shared/tale2/Shared/data/CMRI/PAH-Baseline/Proc/landmark_localisation_annotations/SA'
  SRC_TARGETS: '/shared/tale2/Shared/data/CMRI/PAH-Followup/landmark_localisation_annotations_resized/SA'

  NAME:  "APSIRE_MEDIUM_SA"
  IMAGE_MODALITY: 'CMRI'
  LANDMARKS : [0,1,2,3,]
    
 
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False
  INFERENCE_ONLY: True
  CACHE_DATA: False

INFERENCE:
  EVALUATION_MODE: "scale_heatmap_first" # ["scale_heatmap_first", "scale_pred_coords", "use_input_size"]
  DEBUG: True

SAMPLER:
  NUM_WORKERS: 1
  DATA_AUG: 'AffineComplex'
  INPUT_SIZE : [512,512]

  #TODO: boolean for performing validation or not. its false in the isbi one because it is tested directly instead.