
 
OUTPUT: 
  OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/ISBI/sept22/isbiworkshop/ISBI_jun_3GS_AugAC_gneg_025TS"
 

SOLVER:
  DEEP_SUPERVISION: True
  NUM_RES_SUPERVISIONS: 5
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE: 12
  # MAX_EPOCHS: 3 
  # REGRESS_SIGMA: True





DATASET:
  # DEBUG: True
  ROOT: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks'
  SRC_TARGETS: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks/lann_folds/w_valid10_trainsize0.25/'
  # SRC_TARGETS: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks/lann_folds/w_valid/challenge_test1.json'
  # SRC_TARGETS: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks/lann_folds/w_valid/challenge_test2.json'


  NAME:  "ISBI 2015 Junior"
  IMAGE_MODALITY: 'Cephalometric'
  LANDMARKS : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
  ORIGINAL_IMAGE_SIZE : [1935,2400]
  
 
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False
  CACHE_DATA: True
  INFERENCE_ONLY: False

SAMPLER:
  DATA_AUG: 'AffineComplex'
  INPUT_SIZE : [512,512]
  NUM_WORKERS: 8 
  # DEBUG: True

MODEL:
  GAUSS_SIGMA: 3
  # CHECKPOINT: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/ISBI/sept22/isbiworkshop/ISBI_jun_3GS_AugAC_gneg_025TS/model_best_valid_loss_fold3.model"

OUTPUT:
  COMET_TAGS: ["mimn2"]

INFERENCE:
  DEBUG: False
  # EVALUATION_MODE: "use_input_size" # ["scale_heatmap_first", "scale_pred_coords", "use_input_size"]
