
 
OUTPUT: 
  OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/ISBI/sept22/isbiworkshop/ISBI_challenge_2GS_AugAC_big"
 

SOLVER:
  DEEP_SUPERVISION: True
  NUM_RES_SUPERVISIONS: 5
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE: 12
  # MAX_EPOCHS: 3 
  # REGRESS_SIGMA: True





DATASET:
  # DEBUG: True
  ROOT: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks'
  SRC_TARGETS: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks/lann_folds/w_valid/challenge_training.json'
  NAME:  "ISBI 2015 Junior"
  IMAGE_MODALITY: 'Cephalometric'
  LANDMARKS : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
    
 
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False
  CACHE_DATA: True
  FOLD: -1

SAMPLER:
  DATA_AUG: 'AffineComplex'
  INPUT_SIZE : [640, 800]
  NUM_WORKERS: 8 
  # DEBUG: True

MODEL:
  GAUSS_SIGMA: 2

OUTPUT:
  COMET_TAGS: ["mimn"]