
 
OUTPUT: 
  OUTPUT_DIR: "/home/schobs/Documents/PhD/landmark_ensemble/outputs/256F_12GS_1LM"

SOLVER:
  DEEP_SUPERVISION: False
  NUM_RES_SUPERVISIONS: 1
  LOSS_FUNCTION: "mse"
DATASET:
  LANDMARKS: [0]
  DEBUG: False

MODEL:
  GAUSS_SIGMA: 12
  MAX_FEATURES: 256
