
OUTPUT: 
  OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/ISBI/param_search/ISBI_256F_512Res_8GS_32MFR_AugACE_DS3"
 

SOLVER:
  DEEP_SUPERVISION: True
  NUM_RES_SUPERVISIONS: 3
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE: 12



MODEL:
  GAUSS_SIGMA: 8
  MAX_FEATURES: 256
  MIN_FEATURE_RESOLUTION: 32

DATASET:
  # DEBUG: True
  DATA_AUG: 'AffineComplexElastic'
  ROOT: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks'
  SRC_TARGETS: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks/lann_folds/w_valid'
  NAME:  "ISBI 2015 Junior"
  IMAGE_MODALITY: 'Cephalometric'
  LANDMARKS : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
    
  INPUT_SIZE : [512,512]
 
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False

  #TODO: boolean for performing validation or not. its false in the isbi one because it is tested directly instead.