
OUTPUT: 
  OUTPUT_DIR: "/home/acq19las/landmark_unet/LaNNU-Net/outputsISBI/testing/ISBI_256F_512Res_8GS_32MFR_AugAC_DS3"
 

SOLVER:
  DEEP_SUPERVISION: True
  NUM_RES_SUPERVISIONS: 3
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE_TRAIN: 12
  # REGRESS_SIGMA: True



MODEL:
  GAUSS_SIGMA: 3
  MAX_FEATURES: 256
  MIN_FEATURE_RESOLUTION: 32

DATASET:
  # DEBUG: True
  DATA_AUG: 'AffineComplex'
  ROOT: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks'
  SRC_TARGETS: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks/lann_folds'
  NAME:  "ISBI 2015 Junior"
  IMAGE_MODALITY: 'Cephalometric'
  LANDMARKS : [0]
    
  INPUT_SIZE : [512,512]
 
TRAINER:
  PERFORM_VALIDATION: False
  SAVE_LATEST_ONLY: False

