
 
OUTPUT: 
  OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/GP/isbiTEST"

 
  USE_COMETML_LOGGING: True
  COMET_API_KEY: "B5Nk91E6iCmWvBznXXq3Ijhhp"
  COMET_WORKSPACE: "schobs"

SOLVER:
  DEEP_SUPERVISION: False
  NUM_RES_SUPERVISIONS: 1
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE_TRAIN: -1
  MAX_EPOCHS: 15000 
  MINI_BATCH_SIZE: 1
  # REGRESS_SIGMA: True
  DATA_LOADER_BATCH_SIZE_EVAL: 1
  BASE_LR: 0.1
  AUTO_MIXED_PRECISION: False




DATASET:
  # DEBUG: True
  ROOT: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks'
  SRC_TARGETS: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks/lann_folds/w_valid'
  NAME:  "ISBI 2015 Junior"
  IMAGE_MODALITY: 'Cephalometric'
  LANDMARKS : [0]
  TRAINSET_SIZE: -1  # -1 for full trainset size or int <= len(training_set)

 
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False
  CACHE_DATA: False
  INFERENCE_ONLY: True
  

SAMPLER:
  DATA_AUG: "Flatten"
  INPUT_SIZE : [512,512]
  SAMPLE_MODE: 'patch_centred' # ['patch_bias', 'full', "patch_centred"]
  EVALUATION_SAMPLE_MODE: "patch_centred"  # ['patch_bias', 'full', "patch_centred"]

  NUM_WORKERS: 0
  DEBUG: False
  PATCH:
    SAMPLER_BIAS: 1.0
    RESOLUTION_TO_SAMPLE_FROM:  "input_size"
    SAMPLE_PATCH_SIZE: [64,64]
    # CENTRED_PATCH_COORDINATE_PATH: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/ISBI/param_search/ISBI_512F_512Res_5GS_4MFR_AugAS_DS5/individual_results_allfolds.xlsx"
    CENTRED_PATCH_COORDINATE_PATH: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/GP/unet_s1_preds_test/individual_results_fold0.xlsx"
    CENTRED_PATCH_COORDINATE_PATH_SHEET: "model_best_valid_coord_error_fold0"
    CENTRED_PATCH_JITTER: 0.0

MODEL:
  GAUSS_SIGMA: 2
  ARCHITECTURE: "GP"  # ["U-Net" , "PHD-Net"]
  # CHECKPOINT: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/GP/gp_test1/GPmodel_fold0.model"

INFERENCE:
  EVALUATION_MODE: "use_input_size"  # ["scale_heatmap_first", "scale_pred_coords", "use_input_size"]

SSH: 
  AUTO_AMEND_PATHS: True