
 
OUTPUT: 
  OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/GP/gp_test_128x128_patch_rank2_idx11_longtrain"
 
  USE_COMETML_LOGGING: True
  COMET_API_KEY: "B5Nk91E6iCmWvBznXXq3Ijhhp"
  COMET_WORKSPACE: "schobs"
  COMET_TAGS: ["gp"]

SOLVER:
  DEEP_SUPERVISION: False
  NUM_RES_SUPERVISIONS: 1
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE_TRAIN: 500
  MAX_EPOCHS: 50000 
  # REGRESS_SIGMA: True
  MINI_BATCH_SIZE: 150 

  AUTO_MIXED_PRECISION: False

  BASE_LR: 0.1  # Initial learning rate



DATASET:
  # DEBUG: True
  ROOT: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks'
  SRC_TARGETS: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks/lann_folds/w_valid'
  NAME:  "ISBI 2015 Junior"
  IMAGE_MODALITY: 'Cephalometric'
  LANDMARKS : [11]
    
 
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False
  CACHE_DATA: True
  INFERENCE_ONLY: False
  

SAMPLER:
  DATA_AUG: None
  INPUT_SIZE : [512,512]
  SAMPLE_MODE: 'patch_bias' # ['patch', 'full']
  NUM_WORKERS: 8
  DEBUG: False
  PATCH:
    SAMPLER_BIAS: 1.0
    RESOLUTION_TO_SAMPLE_FROM:  "input_size"
    SAMPLE_PATCH_SIZE: [128,128]

MODEL:
  GAUSS_SIGMA: 2
  ARCHITECTURE: "GP"  # ["U-Net" , "PHD-Net"]
  # CHECKPOINT: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/GP/gp_test1/GPmodel_fold0.model"

INFERENCE:
  EVALUATION_MODE: "use_input_size" # ["scale_heatmap_first", "scale_pred_coords", "use_input_size"]
