
OUTPUT_DIR: "/mnt/bess/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/phdnet/testing/test"
# OUTPUT_DIR: "/home/schobs/Documents/PhD/landmark_ensemble/outputs/4CH_256F_256Res_8GS_AugV1"

SOLVER:
  DEEP_SUPERVISION: False
  LOSS_FUNCTION: "patch_disp_gauss"
  DATA_LOADER_BATCH_SIZE: 12



MODEL:
  GAUSS_SIGMA: 8
  ARCHITECTURE: "PHD-Net"  

DATASET:
  # DEBUG: True
  DATA_AUG: 'AffineComplexElastic'
  ROOT: '/mnt/tale_shared/data/CMRI/ASPIRE'
  SRC_TARGETS: '/mnt/tale_shared/data/CMRI/ASPIRE/cardiac4ch_labels_VPnC_CV'
  NAME:  "ISBI 2015 Junior"
  IMAGE_MODALITY: 'Cephalometric'
  LANDMARKS : [0]
  ORIGINAL_IMAGE_SIZE : [512,512]
  
  INPUT_SIZE : [512,512]
 
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False

  #TODO: boolean for performing validation or not. its false in the isbi one because it is tested directly instead.