

 
OUTPUT: 
  OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/GP/s1/f2_val/"

  USE_COMETML_LOGGING: True
  COMET_API_KEY: "B5Nk91E6iCmWvBznXXq3Ijhhp"
  COMET_WORKSPACE: "schobs"

SOLVER:
  DEEP_SUPERVISION: True
  NUM_RES_SUPERVISIONS: 5
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE_TRAIN: 12
  # MAX_EPOCHS: 258
  # REGRESS_SIGMA: True


INFERENCE:

  SPLIT: "validation"
  SAVE_INTERMEDIATE_OUTPUTS_ONLY: True


DATASET:
  # DEBUG: True
  ROOT: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks'
  SRC_TARGETS: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks/lann_folds/w_valid'
  NAME:  "ISBI 2015 Junior"
  IMAGE_MODALITY: 'Cephalometric'
  LANDMARKS : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
    
 
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False
  CACHE_DATA: False
  INFERENCE_ONLY: True
  FOLD: 2
  VALIDATION_LOG_HEATMAPS: False
  
SAMPLER:
  DATA_AUG: 'AffineComplex'
  INPUT_SIZE : [512,512]
  NUM_WORKERS: 0

MODEL:
  GAUSS_SIGMA: 5

  CHECKPOINT: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/ISBI/param_search/ISBI_512F_512Res_5GS_4MFR_AugAC_DS5//model_best_valid_coord_error_fold2.model"


SSH: 
  AUTO_AMEND_PATHS: False
