
OUTPUT_DIR: "/mnt/bess/home/acq19las/landmark_unet/LaNNU-Net/test/4CH_512F_512Res_8GS_AugV1_AWingL"
# OUTPUT_DIR: "/home/schobs/Documents/PhD/landmark_ensemble/outputs/4CH_256F_256Res_8GS_AugV1"

SOLVER:
  DEEP_SUPERVISION: False
  NUM_RES_SUPERVISIONS: 1
  LOSS_FUNCTION: "awl"
  DATA_LOADER_BATCH_SIZE: 12



MODEL:
  GAUSS_SIGMA: 8
  MAX_FEATURES: 512
  HM_LAMBDA_SCALE: 100.0

DATASET:
  DEBUG: False
  INPUT_SIZE: [512,512]
  DATA_AUG: 'V1'
  ROOT: '/mnt/bess/home/acq19las/data/ASPIRE'
  SRC_TARGETS: '/mnt/bess/home/acq19las/data/ASPIRE/cardiac4ch_labels_VPnC_CV'
  