
 
OUTPUT: 
  OUTPUT_DIR: "/mnt/tale/outputs/4CH_256F_256Res_12GS"

SOLVER:
  DEEP_SUPERVISION: False
  NUM_RES_SUPERVISIONS: 1
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE: 6 



MODEL:
  GAUSS_SIGMA: 12
  MAX_FEATURES: 256

DATASET:
  ROOT: '/mnt/bess/home/acq19las/data/ASPIRE/'
  SRC_TARGETS: '/mnt/bess/home/acq19las/data/ASPIRE/cardiac4ch_labels_VPnC_CV'
  DEBUG: False
  INPUT_SIZE: [256,256]
  # DATA_AUG: 'V1'
  
INFERENCE:
  EVALUATION_MODE: "scale_heatmap_first"  # ["scale_heatmap_first", "scale_pred_coords", "use_input_size"]



