
 
OUTPUT: 
  OUTPUT_DIR: "/home/schobs/Documents/PhD/landmark_ensemble/outputs/4CH_256F_256Res_8GS_3LM"

SOLVER:
  DEEP_SUPERVISION: False
  NUM_RES_SUPERVISIONS: 1
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE: 6 

DATASET:
  LANDMARKS: [0,1,2]
  DEBUG: False

MODEL:
  GAUSS_SIGMA: 8
  MAX_FEATURES: 256

DATASET:
  ROOT: '/mnt/tale_shared/data/CMRI/ASPIRE/'
  SRC_TARGETS: '/mnt/tale_shared/data/CMRI/ASPIRE/cardiac4ch_labels_VPnC_CV'
  DEBUG: True
  INPUT_SIZE: [256,256]
  