
OUTPUT_DIR: "/mnt/bess/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/ISBI/testing/t2"
# OUTPUT_DIR: "/home/schobs/Documents/PhD/landmark_ensemble/outputs/4CH_256F_256Res_8GS_AugV1"

SOLVER:
  DEEP_SUPERVISION: True
  NUM_RES_SUPERVISIONS: 5
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE: 12
  MAX_EPOCHS: 1000
  REGRESS_SIGMA: True
  REGRESS_SIGMA_LOSS_WEIGHT: 0.005
  AUTO_MIXED_PRECISION: True


# /mnt/bess/home/acq19las/landmark_unet/LaNNU-Net/outputsISBI/v2/ISBI_512F_512Res_3GS_4MFR_AugACEBS_DS5

MODEL:
  GAUSS_SIGMA: 12
  MAX_FEATURES: 512
  MIN_FEATURE_RESOLUTION: 4

DATASET:
  # DEBUG: True
  DATA_AUG: 'AffineComplex'
  ROOT: '/mnt/bess/shared/tale2/Shared/schobs/data/ISBI2015_landmarks'
  SRC_TARGETS: '/mnt/bess/shared/tale2/Shared/schobs/data/ISBI2015_landmarks/lann_folds/w_valid'
  NAME:  "ISBI 2015 Junior"
  IMAGE_MODALITY: 'Cephalometric'
  LANDMARKS : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
  ORIGINAL_IMAGE_SIZE : [1935,2400]
  NUM_WORKERS: 0

  INPUT_SIZE : [512,512]
 
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False
  CACHE_DATA: False

