
OUTPUT: 
  OUTPUT_DIR: "home/acq19las/landmark_unet/LaNNU-Net/outputs/4CH_512F_512Res_8GS_AugV1_AWingL"
 

SOLVER:
  DEEP_SUPERVISION: False
  NUM_RES_SUPERVISIONS: 1
  LOSS_FUNCTION: "awl"
  DATA_LOADER_BATCH_SIZE_TRAIN: 12



MODEL:
  GAUSS_SIGMA: 8
  MAX_FEATURES: 512
  HM_LAMBDA_SCALE: 100.0

DATASET:
  DEBUG: False
  INPUT_SIZE: [512,512]
  DATA_AUG: 'V1'
  ROOT: '/home/acq19las/data/ASPIRE'
  SRC_TARGETS: '/home/acq19las/data/ASPIRE/cardiac4ch_labels_VPnC_CV'
  