
OUTPUT_DIR: "/home/acq19las/landmark_unet/LaNNU-Net/outputs2/4CH_512F_256Res_8GS_AugV2"
# OUTPUT_DIR: "/home/schobs/Documents/PhD/landmark_ensemble/outputs/4CH_256F_256Res_8GS_AugV1"

SOLVER:
  DEEP_SUPERVISION: False
  NUM_RES_SUPERVISIONS: 1
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE: 48



MODEL:
  GAUSS_SIGMA: 8
  MAX_FEATURES: 512

DATASET:
  DEBUG: False
  INPUT_SIZE: [256,256]
  DATA_AUG: 'V2'
  ROOT: '/home/acq19las/data/ASPIRE'
  SRC_TARGETS: '/home/acq19las/data/ASPIRE/cardiac4ch_labels_VPnC_CV'
  