
OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/ISBI/testing/t5"
# OUTPUT_DIR: "/home/schobs/Documents/PhD/landmark_ensemble/outputs/4CH_256F_256Res_8GS_AugV1"

SOLVER:
  DEEP_SUPERVISION: True
  NUM_RES_SUPERVISIONS: 5
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE: 12
  MAX_EPOCHS: 10005
  # REGRESS_SIGMA: True
  REGRESS_SIGMA_LOSS_WEIGHT: 0.005
  AUTO_MIXED_PRECISION: True
  MINI_BATCH_SIZE: 150

 
# /mnt/bess/home/acq19las/landmark_unet/LaNNU-Net/outputsISBI/v2/ISBI_512F_512Res_3GS_4MFR_AugACEBS_DS5

MODEL:
  GAUSS_SIGMA: 8
  UNET:
    MAX_FEATURES: 512
    MIN_FEATURE_RESOLUTION: 4
  CHECKPOINT: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/ISBI/param_search/ISBI_512F_512Res_8GS_4MFR_AugAC_DS5/model_best_valid_coord_error_fold0.model"
  # CHECKPOINT: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/ISBI/testing/t3/model_ep_299_fold0.model"
  # CHECKPOINT: "/shared/tale2/Shared/schobs/landmark_unet/lannUnet_exps/ISBI/testing/t5/model_best_valid_coord_error_fold0.model"

DATASET:
  # DEBUG: True
  
  ROOT: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks'
  SRC_TARGETS: '/shared/tale2/Shared/schobs/data/ISBI2015_landmarks/lann_folds/w_valid'
  NAME:  "ISBI 2015 Junior"
  IMAGE_MODALITY: 'Cephalometric'
  LANDMARKS : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
  # LANDMARKS : [8]

  ORIGINAL_IMAGE_SIZE : [1935,2400]


SAMPLER:
  DATA_AUG: 'AffineComplex'
  INPUT_SIZE : [512,512]
  SAMPLE_MODE: 'full' # ['patch', 'full']
  NUM_WORKERS: 8
  # DEBUG: True
  PATCH:
    SAMPLER_BIAS: 0.66
    RESOLUTION_TO_SAMPLE_FROM:  [512,512]
    SAMPLE_PATCH_SIZE: [128,128]


# _C.SAMPLER.PATCH = CN() 
# _C.SAMPLER.PATCH.SAMPLE_PATCH_SIZE = [512,512]
# _C.SAMPLER.PATCH.SAMPLE_FROM_RESOLUTION = _C.DATASET.ORIGINAL_IMAGE_SIZE #Default samples from full resolution image.
# _C.SAMPLER.PATCH.SAMPLER_BIAS = 0.66
TRAINER:
  PERFORM_VALIDATION: True
  SAVE_LATEST_ONLY: False
  CACHE_DATA: False

  INFERENCE_ONLY: False
