
OUTPUT: 
  OUTPUT_DIR: "/shared/tale2/Shared/schobs/landmark_unet/ensemble/outputs/4CH_256F_256Res_8GS_AugV1"
 

SOLVER:
  DEEP_SUPERVISION: False
  NUM_RES_SUPERVISIONS: 1
  LOSS_FUNCTION: "mse"
  DATA_LOADER_BATCH_SIZE: 6 



MODEL:
  GAUSS_SIGMA: 8
  MAX_FEATURES: 256

DATASET:
  DEBUG: False
  INPUT_SIZE: [256,256]
  DATA_AUG: 'V1'
  