# Config File to run the LaNNU-Net on the ISBI 2015 Junior dataset (cephalometric landmarks).
# Change: 1) Comet details (or remove them).
#         2) DATASET.ROOT and DATASET.SRC_TARGETS to your source (I do not have permission to upload the data).
# If you want to do a different fold, use a different checkpoint i.e. unet_cephalometric_foldX.yaml where X is fold.
# To combine the results and get evaluation statistics for all folds, change details in evaluation/analyse_results_isbi.py and run it.
 
OUTPUT: 
  OUTPUT_DIR: "../outputs/unet_cephalometric_example_train/"
  USE_COMETML_LOGGING: True
  COMET_API_KEY: "B5Nk91E6iCmWvBznXXq3Ijhhp"
  COMET_WORKSPACE: "schobs"

SOLVER:
  DEEP_SUPERVISION: True
  NUM_RES_SUPERVISIONS: 5
  DATA_LOADER_BATCH_SIZE_EVAL: 12
  DATA_LOADER_BATCH_SIZE_TRAIN: 12
  MAX_EPOCHS: 500
  MINI_BATCH_SIZE: 150
  EARLY_STOPPING_PATIENCE: 150

INFERENCE:
  SPLIT: "testing"


DATASET:

  ROOT: '/home/schobs/Documents/PhD/data/ISBI2015_landmarks' # FILL IN WITH YOUR DATASET ROOT
  SRC_TARGETS: '//home/schobs/Documents/PhD/data/ISBI2015_landmarks/lann_folds/w_valid'  # FILL IN WITH YOUR LABELS ROOT
  NAME:  "ISBI 2015 Junior"
  IMAGE_MODALITY: 'Cephalometric'
  LANDMARKS : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
    
 
TRAINER:
  PERFORM_VALIDATION: True
  INFERENCE_ONLY: True
  FOLD: 0
  CACHE_DATA: False
  SAVE_EVERY: 50

SAMPLER:
  INPUT_SIZE : [512,512]
  NUM_WORKERS: 2
  DATA_AUG: 'AffineComplex'

MODEL:
  GAUSS_SIGMA: 8
  ARCHITECTURE: "U-Net"
  UNET:
    MIN_FEATURE_RESOLUTION: 4
    MAX_FEATURES: 512
    INIT_FEATURES: 32

