# Config File to run the LaNNU-Net on the ISBI 2015 Junior dataset (cephalometric landmarks).
# Change: 1) Comet details (or remove them).
#         2) DATASET.ROOT and DATASET.SRC_TARGETS to your source (I do not have permission to upload the data).
# If you want to do a different fold, use a different checkpoint i.e. unet_cephalometric_foldX.yaml where X is fold.
# To combine the results and get evaluation statistics for all folds, change details in evaluation/analyse_results_isbi.py and run it.
 
OUTPUT: 
  OUTPUT_DIR: "../outputs/unet_cephalometric_example/"
  USE_COMETML_LOGGING: True
  COMET_API_KEY: "B5Nk91E6iCmWvBznXXq3Ijhhp"
  COMET_WORKSPACE: "schobs"

SOLVER:
  DEEP_SUPERVISION: True
  NUM_RES_SUPERVISIONS: 5
  DATA_LOADER_BATCH_SIZE_EVAL: 12


INFERENCE:
  SPLIT: "testing"
  DEBUG: False


DATASET:
  ROOT: '/home/schobs/Documents/PhD/data/ISBI2015_landmarks' # FILL IN WITH YOUR DATASET ROOT
  SRC_TARGETS: '//home/schobs/Documents/PhD/data/ISBI2015_landmarks/lann_folds/w_valid'  # FILL IN WITH YOUR LABELS ROOT
  NAME:  "ISBI 2015 Junior"
  IMAGE_MODALITY: 'Cephalometric'
  LANDMARKS : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
    
 
TRAINER:
  INFERENCE_ONLY: True
  FOLD: 3

SAMPLER:
  INPUT_SIZE : [512,512]
  NUM_WORKERS: 2

MODEL:
  CHECKPOINT: "./LaNNU-Net/model_zoo/Cephalometric/U-Net/model_best_valid_coord_error_fold3.model"
  MODEL_GDRIVE_DL_PATH: "https://drive.google.com/file/d/1oCFfm_n09y2ZY1-5uNulfCganqfO5VPL/view?usp=share_link"


